kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "roundcube.fullname" . }}-conf
  labels:
    {{- include "roundcube.labels" . | nindent 4 }}
data:
  ports.conf: |
    Listen 0.0.0.0:80
  config.inc.php: |
    <?php
    // Custom Roundcube configuration
    // Disable SMTP authentication - use anonymous relay to internal mail server
    $config['smtp_user'] = '';
    $config['smtp_pass'] = '';
    ?>
