apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "roundcube.fullname" . }}-data
spec:
  accessModes:
    - {{ .Values.pvc.accessModes | default "ReadWriteMany" | quote }}
  storageClassName: {{ .Values.pvc.storageClassName | default "default" | quote }}
  {{- if .Values.pvc.volumeName }}
  volumeName: {{ .Values.pvc.volumeName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.size | default "500M" | quote }}
