---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: awx-ingress
  namespace: awx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
    nginx.ingress.kubernetes.io/auth-url: "https://oauth2-proxy.home.planetlauritsen.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-proxy.home.planetlauritsen.com/oauth2/start?rd=https://$host$request_uri"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - awx.home.planetlauritsen.com
      secretName: awx-tls # pragma: allowlist secret
  rules:
    - host: awx.home.planetlauritsen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: awx-external
                port:
                  number: 8052

