---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: awx-ingress
  namespace: awx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - awx.home.planetlauritsen.com
      secretName: awx-tls # pragma: allowlist secret
  rules:
    - host: awx.home.planetlauritsen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: awx-external
                port:
                  number: 8052

