---
apiVersion: v1
kind: Service
metadata:
  name: awx-external
  namespace: awx
spec:
  type: ExternalName
  externalName: wmini.planetlauritsen.com
  ports:
    - name: http
      port: 8052
      targetPort: 8052
      protocol: TCP


