- name: Update all packages to the latest version
  hosts: debian
  tasks:
   - name: Clean apt cache
     become: yes
     ansible.builtin.command: apt-get clean
     changed_when: false
   - name: Update apt cache
     become: yes
     ansible.builtin.command: apt-get update
     changed_when: false
   - name: Apt upgrade
     become: yes
     ansible.builtin.apt:
       update_cache: yes
       upgrade: dist
       autoremove: yes
