$ANSIBLE_VAULT;1.1;AES256
66636366643239376262376636373464343062646230366434646563623337313062373163326265
6435313233613530383731366632616134613635313430310a353466353339313964383035306236
61666537653935376266616634663736326332633432363036336133626332336664316665626563
6564636638636137320a643264333634303039373765393133333163376330366234303235306636
66613434333330353531636565343433623539343039396432393038626163653963646366343965
33313733346432633261373265383235626365323466653163636530353033356334353933313663
65353535316561653934666465636262613935613362333930643131656236643438373638343439
66653931613539343864326136383662363338383231663538643439326630356264326633313936
30303535306235333138323266613363383635373064306332343965646161383832393138316665
3230373231613739386537336533643239363564656139646437
